<?php
/**
 * @var \IdealCode\Banner\Block\Widget\ItemList $block
 */
?>
<div>
    <?php foreach ($block->getItems() as $item):?>
        <div class="item">
            <?php if (strlen($item['link']) > 0 ):?>
                <a href="<?=$item['link']?>">
            <?php endif; ?>
                <?php if (strlen($item['img']) > 0 ):?>
                    <img src="<?=$item['img']?>">
                <?php endif; ?>
                <?php if (strlen($item['content']) > 0 ):?>
                    <div>
                        <?=$item['content']?>
                    </div>
                <?php endif; ?>
            <?php if (strlen($item['link']) > 0 ):?>
                </a>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
